version: '3.7'

services:
  journal_db:
    image: postgres:alpine
    restart: on-failure
    container_name: journal_pg_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: journal_db
    volumes:
      - journal_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  sender_db:
    image: postgres:alpine
    restart: on-failure
    container_name: sender_pg_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: sender_db
    volumes:
      - sender_pg_data:/var/lib/postgresql/data
    ports:
      - 6432:5432
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  journal_pg_data:
  sender_pg_data:


