version: '3.7'

services:
  db:
    image: postgres
    restart: on-failure
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: journal_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg_data:

